env:
  node: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
rules:
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/explicit-module-boundary-types': off
ignorePatterns:
  - 'lib/**/*.d.ts'
