name: Lizard Runner
on:
  workflow_run:
      workflows: ["CodeQL"]
      branches: [main]
      types:
        - completed

jobs:
  lizard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lizard Runner
        uses: Uno-Takashi/Lizard-Runner@v3
